import { createHmac, timingSafeEqual } from 'node:crypto';
import { env } from './env';

// Signs "register on check-in" for one event so only a QR generated by an admin
// can trigger registrations; a hand-crafted POST or tweaked link can't. Keyed
// off the service-role key (server-only) so no extra secret needs configuring.
function sign(eventId: string): string | null {
  const secret = env('SUPABASE_SERVICE_ROLE_KEY');
  if (!secret) return null;
  return createHmac('sha256', secret).update(`checkin-register:${eventId}`).digest('hex');
}

export function createCheckinRegisterToken(eventId: string): string | null {
  return sign(eventId);
}

export function verifyCheckinRegisterToken(eventId: string, token: string | null | undefined): boolean {
  const expected = sign(eventId);
  if (!expected || !token || token.length !== expected.length) return false;
  return timingSafeEqual(Buffer.from(token), Buffer.from(expected));
}
